[project]
name = "agentic"
version = "0.1.0"
description = "CAPSTONE assessment"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai<=0.118",
    "crewai-tools>=0.44.0",
    "langtrace-python-sdk>=3.8.18",
    "python-dotenv>=1.0.0",
]
