[project]
name = "agentic"
version = "0.1.0"
description = "CAPSTONE assessment"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.120.1",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "crewai-tools>0.45.0"
]
